from matplotlib import pyplot as plb
import matplotlib as plt
plb.rc('xtick', labelsize=14) 
plb.rc('ytick', labelsize=14)

f1=plb.figure(figsize=(10,6))
plb.plot(trange,mediacop000,marker='o',linestyle='--',label='q=1')
plb.plot(trange,mediacop001,marker='o',linestyle='--',label='q=0.99')
plb.plot(trange,mediacop002,marker='o',linestyle='--',label='q=0.9')
plb.plot(trange,mediacop003,marker='o',linestyle='--',label='q=0.75')
plb.plot(trange,mediacop004,marker='o',linestyle='--',label='q=0.5')
plb.plot(trange,mediacop005,marker='o',linestyle='--',label='q=0.25')
plb.plot(trange,mediacop,marker='o',linestyle='--',label='q=0')


plb.title('Fraction of Cooperators',fontsize=16)
plb.xlabel('b',fontsize=16)
plb.ylabel('Fraction of Cooperators',fontsize=16)
plb.legend()
f1.savefig('FractionofCooperators.jpg')

f2=plb.figure(figsize=(10,6))
plb.plot(trange,varianzanorm000,marker='o',linestyle='--',label='q=1')
plb.plot(trange,varianzanorm001,marker='o',linestyle='--',label='q=0.99')
plb.plot(trange,varianzanorm002,marker='o',linestyle='--',label='q=0.9')
plb.plot(trange,varianzanorm003,marker='o',linestyle='--',label='q=0.75')
plb.plot(trange,varianzanorm004,marker='o',linestyle='--',label='q=0.5')
plb.plot(trange,varianzanorm005,marker='o',linestyle='--',label='q=0.25')
plb.plot(trange,varianzanorm,marker='o',linestyle='--',label='q=0')
plb.title('Normalized variance',fontsize=16)
plb.xlabel('b',fontsize=16)
plb.ylabel('Normalized variance',fontsize=16)
plb.legend()
f2.savefig('NormalizedVariance.jpg')

f3=plb.figure()
plb.plot(trange,payoffdif000,marker='o',linestyle='--',label='q=1')
plb.plot(trange,payoffdif001,marker='o',linestyle='--',label='q=0.99')
plb.plot(trange,payoffdif002,marker='o',linestyle='--',label='q=0.9')
plb.plot(trange,payoffdif003,marker='o',linestyle='--',label='q=0.75')
plb.plot(trange,payoffdif004,marker='o',linestyle='--',label='q=0.5')
plb.plot(trange,payoffdif005,marker='o',linestyle='--',label='q=0.25')
plb.plot(trange,payoffdif,marker='o',linestyle='--',label='q=0')
plb.title('Difference in payoffs')
plb.xlabel('b')
plb.ylabel('Pd-Pc')
plb.legend()
f3.savefig('Payoffdif.jpg')